# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visibility', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=200)),
                ('re_validation', models.CharField(max_length=200)),
                ('max_values', models.IntegerField(default=1)),
                ('value', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japps.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visibility', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=200)),
                ('re_validation', models.CharField(max_length=200)),
                ('max_values', models.IntegerField(default=1)),
                ('value', models.FloatField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japps.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visibility', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=200)),
                ('re_validation', models.CharField(max_length=200)),
                ('max_values', models.IntegerField(default=1)),
                ('value', models.CharField(max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japps.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='app',
        ),
        migrations.AlterField(
            model_name='input',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='japps.Application'),
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
