# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japps', '0002_auto_20161013_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanparameter',
            name='app',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='japps.Application'),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='label',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='max_values',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='re_validation',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='booleanparameter',
            name='visibility',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='app',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='japps.Application'),
        ),
        migrations.AlterField(
            model_name='input',
            name='label',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='input',
            name='max_values',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='input',
            name='requirement',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='app',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='japps.Application'),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='label',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='max_values',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='re_validation',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='numericalparameter',
            name='visibility',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='app',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='japps.Application'),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='label',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='max_values',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='re_validation',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='textparameter',
            name='visibility',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
