# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japps', '0003_auto_20161017_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanparameter',
            name='app',
        ),
        migrations.RemoveField(
            model_name='input',
            name='app',
        ),
        migrations.RemoveField(
            model_name='numericalparameter',
            name='app',
        ),
        migrations.RemoveField(
            model_name='textparameter',
            name='app',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='BooleanParameter',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='NumericalParameter',
        ),
        migrations.DeleteModel(
            name='TextParameter',
        ),
    ]
