# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japps', '0004_auto_20161129_1546'),
    ]

    operations = [
    ]
